"""
技术雷达静态配置 — 14个技术领域映射表 + 用户持仓配置
"""
from typing import Any, Dict, List

# ═══════════════════════════════════════
#  用户持仓（与 StockWatcher 同步）
# ═══════════════════════════════════════
HOLDINGS: List[Dict[str, str]] = [
    {"code": "601899", "name": "紫金矿业", "tag": "核心持仓"},
    {"code": "600089", "name": "特变电工", "tag": "核心持仓"},
    {"code": "603596", "name": "伯特利",   "tag": "核心持仓"},
    {"code": "600584", "name": "长电科技", "tag": "重点观察"},
    {"code": "301018", "name": "申菱环境", "tag": "重点观察"},
    {"code": "688981", "name": "中芯国际", "tag": "重点观察"},
    {"code": "688295", "name": "中复神鹰", "tag": "等回调"},
    {"code": "601126", "name": "四方股份", "tag": "等回调"},
    {"code": "300699", "name": "光威复材", "tag": "埋伏"},
    {"code": "000960", "name": "锡业股份", "tag": "埋伏"},
    {"code": "600111", "name": "北方稀土", "tag": "埋伏"},
    {"code": "603259", "name": "药明康德", "tag": "买不起"},
    {"code": "002837", "name": "英维克",   "tag": "关注"},
    {"code": "002335", "name": "科华数据", "tag": "关注"},
]

# HOLDING_CODE_TO_NAME 快速查找
HOLDING_CODE_MAP: Dict[str, str] = {h["code"]: h["name"] for h in HOLDINGS}

# ═══════════════════════════════════════
#  14 个核心技术领域完整配置
# ═══════════════════════════════════════
TECH_RADAR_CONFIG: List[Dict[str, Any]] = [
    # ────────── AI ──────────
    {
        "id": "ai_edge_llm", "area": "AI · 端侧大模型",
        "tech_name": "端侧大模型：2bit/1.5bit混合量化+投机解码",
        "keywords": ["端侧大模型", "混合精度量化", "BitNet b1.58", "手机本地大模型",
                     "端侧AI芯片", "NPU推理", "投机解码", "KV缓存压缩"],
        "stocks": [{"code":"603893","name":"瑞芯微","tag":"端侧NPU芯片"},
                   {"code":"300458","name":"全志科技","tag":"端侧AI SoC"},
                   {"code":"688018","name":"乐鑫科技","tag":"AIoT芯片"}],
        "your_holdings_mapped": ["中芯国际(688981)"],
        "breakthrough_year": "2027-2028", "progress_pct": 35,
        "progress_desc": "BitNet b1.58论文已发，手机端70B推理demo跑通，NPU适配进行中",
        "principle": "注意力层3bit+FFN层三值化(~1.58bit)+KV缓存压缩+投机解码，压70B到手机",
        "bottleneck": "①超低位宽量化数学推理掉点 ②长上下文压缩后语义断层 ③端侧NPU不适配",
        "rnd_orgs": "清华朱军(BitNet)、微软1-bit LLM、高通AI、联发科、华为诺亚",
    },
    {
        "id": "ai_agent", "area": "AI · Agent智能体",
        "tech_name": "AI Agent：长期记忆+任务拆解+自我纠错",
        "keywords": ["AI Agent","智能体","MCP协议","模型上下文协议","任务拆解","工具调用","ReAct","长期记忆"],
        "stocks": [{"code":"688111","name":"金山办公","tag":"WPS AI Agent"},
                   {"code":"300170","name":"汉得信息","tag":"企业Agent实施"},
                   {"code":"603039","name":"泛微网络","tag":"OA Agent"}],
        "your_holdings_mapped": [],
        "breakthrough_year": "2027-2028", "progress_pct": 30,
        "progress_desc": "MCP标准Anthropic推出快速普及，Agent框架发布，长期记忆仍不成熟",
        "principle": "向量数据库长期记忆挂载+分层规划+执行复盘修正闭环+MCP协议",
        "bottleneck": "①长期记忆混乱遗忘 ②复杂任务拆解弱 ③多轮工具调用逻辑崩塌",
        "rnd_orgs": "Anthropic(MCP)、OpenAI、斯坦福ReAct、清华、微软、阿里钉钉",
    },
    {
        "id": "ai_multimodal", "area": "AI · 原生多模态",
        "tech_name": "原生多模态：统一表征+MoE架构",
        "keywords": ["多模态大模型","MoE多模态","视频理解","时空Transformer","图文音视频统一","Sora"],
        "stocks": [{"code":"300624","name":"万兴科技","tag":"视频创意AI"},
                   {"code":"300418","name":"昆仑万维","tag":"多模态AI"}],
        "your_holdings_mapped": [],
        "breakthrough_year": "2027", "progress_pct": 40,
        "progress_desc": "GPT-4V/Gemini/豆包迭代中，MoE降本效果显著",
        "principle": "时空Transformer+3D卷积+MoE，文/图/音/视频统一语义空间",
        "bottleneck": "①表征不互通 ②长视频时间轴逻辑差 ③训练数据配比失衡",
        "rnd_orgs": "Google Gemini、OpenAI、字节豆包、上海AI实验室、清华",
    },
    {
        "id": "ai_explainability", "area": "AI · 大模型可解释性",
        "tech_name": "大模型可解释性：SAE+因果溯源+激活工程",
        "keywords": ["大模型可解释性","机制可解释性","稀疏自编码器","SAE","因果溯源","激活工程"],
        "stocks": [],
        "your_holdings_mapped": [],
        "breakthrough_year": "2028+", "progress_pct": 20,
        "progress_desc": "Anthropic SAE有突破，距金融/医疗落地仍需3-5年",
        "principle": "SAE解剖模型内部特征+反事实分析+注意力层权重溯源",
        "bottleneck": "无法定位决策真实逻辑，只能表面可视化",
        "rnd_orgs": "Anthropic、MIT、伯克利、清华、IBM、谷歌",
    },
    # ────────── 半导体 ──────────
    {
        "id": "semicon_advanced_pkg", "area": "半导体 · 先进封装",
        "tech_name": "2.5D/3D先进封装：CoWoS→混合键合→玻璃基板",
        "keywords": ["先进封装","Chiplet","CoWoS","混合键合","玻璃基板","XDFOI","TSV硅通孔","UCIe"],
        "stocks": [{"code":"600584","name":"长电科技","tag":"XDFOI"},{"code":"002156","name":"通富微电","tag":"VISionS"},
                   {"code":"002185","name":"华天科技","tag":"先进封装"},{"code":"603773","name":"沃格光电","tag":"玻璃基板"},
                   {"code":"688521","name":"芯原股份","tag":"Chiplet IP"}],
        "your_holdings_mapped": ["长电科技(600584)","中芯国际(688981)"],
        "breakthrough_year": "2027-2028", "progress_pct": 50,
        "progress_desc": "台积电CoWoS-L量产，长电XDFOI/通富VISionS追赶，玻璃基板是下一代",
        "principle": "晶圆级混合键合+TSV硅通孔+中介层互连，CoWoS-L用LSI替换整块硅中介层",
        "bottleneck": "①混合键合良率低 ②堆叠散热失控 ③TSV缺陷率高",
        "rnd_orgs": "台积电CoWoS-L、长电XDFOI、通富VISionS、华为2012",
    },
    {
        "id": "semicon_compute_storage", "area": "半导体 · 存算一体",
        "tech_name": "存算一体：RRAM/MRAM/SRAM存内计算",
        "keywords": ["存算一体","存内计算","RRAM","MRAM","近存计算","内存墙","AI推理加速"],
        "stocks": [{"code":"688416","name":"恒烁股份","tag":"NOR Flash存算"},
                   {"code":"300223","name":"北京君正","tag":"存储芯片"}],
        "your_holdings_mapped": [],
        "breakthrough_year": "2027-2029", "progress_pct": 30,
        "progress_desc": "SRAM存内计算台积电有IP，RRAM/NOR Flash路线在研发中",
        "principle": "RRAM/MRAM/SRAM把存储单元当计算单元，跳过CPU内存搬运",
        "bottleneck": "①模拟精度误差大 ②阵列噪声高 ③编译器不兼容",
        "rnd_orgs": "三星、美光、台积电、地平线、知存科技、恒烁股份",
    },
    {
        "id": "semicon_chiplet", "area": "半导体 · Chiplet标准",
        "tech_name": "Chiplet UCIe标准互联：中国版Chiplet生态",
        "keywords": ["Chiplet","UCIe","小芯片","芯粒","先进封装互联","chiplet标准"],
        "stocks": [{"code":"688521","name":"芯原股份","tag":"Chiplet IP"},{"code":"600584","name":"长电科技","tag":"Chiplet封装"}],
        "your_holdings_mapped": ["长电科技(600584)"],
        "breakthrough_year": "2027-2029", "progress_pct": 40,
        "progress_desc": "UCIe 1.0/2.0标准发布，中国Chiplet联盟成立",
        "principle": "UCIe标准把不同工艺不同厂商的小芯片拼成一颗，绕过EUV限制",
        "bottleneck": "①UCIe国内适配未完成 ②跨厂商IP互通难 ③测试验证不成熟",
        "rnd_orgs": "中国Chiplet联盟、华为、中芯国际、长电科技",
    },
    # ────────── 电池能源 ──────────
    {
        "id": "energy_solid_state", "area": "电池 · 全固态",
        "tech_name": "全固态电池：硫化物电解质+锂金属负极 400Wh/kg+",
        "keywords": ["全固态电池","硫化物固态电解质","锂金属负极","固态电池量产","固态电池突破","宁德时代 固态","比亚迪 固态"],
        "stocks": [{"code":"300750","name":"宁德时代","tag":"全固态龙头"},{"code":"002460","name":"赣锋锂业","tag":"固态电解质"},
                   {"code":"300073","name":"当升科技","tag":"固态前驱体"},{"code":"688005","name":"容百科技","tag":"高镍正极"},
                   {"code":"603663","name":"三祥新材","tag":"硫化物原料"}],
        "your_holdings_mapped": ["紫金矿业(601899)"],
        "breakthrough_year": "2027-2028", "progress_pct": 40,
        "progress_desc": "比亚迪/宁德时代宣布2027量产，固-固界面阻抗仍是最大障碍",
        "principle": "硫化物固态电解质+锂金属负极，400Wh/kg+，不燃不爆，15-20min快充",
        "bottleneck": "①固-固界面阻抗极大 ②锂枝晶穿刺 ③稳定性差 ④成本极高",
        "rnd_orgs": "清华张强、比亚迪、宁德时代、丰田、赣锋锂业、卫蓝新能源",
    },
    {
        "id": "energy_sodium_ion", "area": "电池 · 钠离子",
        "tech_name": "钠离子电池：层状氧化物+普鲁士蓝双路线",
        "keywords": ["钠离子电池","钠电","普鲁士蓝","层状氧化物","硬碳负极","钠电储能"],
        "stocks": [{"code":"002866","name":"传艺科技","tag":"钠电正极+电芯"},{"code":"600152","name":"维科技术","tag":"钠电电芯"}],
        "your_holdings_mapped": [],
        "breakthrough_year": "2026-2028", "progress_pct": 55,
        "progress_desc": "钠电储能示范+两轮车放量，成本比锂电低30%",
        "principle": "层状氧化物(中科海钠)+普鲁士蓝白双路线替代锂资源",
        "bottleneck": "①层状氧化物循环衰减 ②普鲁士蓝结构易塌陷 ③硬碳容量偏低",
        "rnd_orgs": "中科院物理所、宁德时代、中科海钠、国轩高科",
    },
    {
        "id": "energy_perovskite", "area": "电池 · 钙钛矿光伏",
        "tech_name": "钙钛矿叠层：晶硅+钙钛矿两端叠层 效率>43%",
        "keywords": ["钙钛矿","钙钛矿叠层","钙钛矿晶硅叠层","光伏效率突破","钙钛矿量产"],
        "stocks": [{"code":"600586","name":"金晶科技","tag":"TCO导电玻璃"},{"code":"300585","name":"奥联电子","tag":"钙钛矿设备"}],
        "your_holdings_mapped": ["特变电工(600089)"],
        "breakthrough_year": "2027-2029", "progress_pct": 35,
        "progress_desc": "隆基34.6%实验室记录，Oxford PV小批量，大面积工艺待突破",
        "principle": "在传统硅电池上镀钙钛矿薄膜分吸长短波，理论效率43%",
        "bottleneck": "①怕水氧仅几千小时 ②大面积均匀性差 ③封装未成熟",
        "rnd_orgs": "隆基、晶科、Oxford PV、极电光能、协鑫光电",
    },
    # ────────── 机器人 ──────────
    {
        "id": "robot_humanoid", "area": "机器人 · 人形机器人",
        "tech_name": "人形机器人：微型伺服+柔性灵巧手",
        "keywords": ["人形机器人","灵巧手","伺服驱动器","Optimus","人形机器人量产","优必选","宇树","智元"],
        "stocks": [{"code":"688017","name":"绿的谐波","tag":"谐波减速器"},{"code":"603728","name":"鸣志电器","tag":"空心杯电机"},
                   {"code":"601689","name":"拓普集团","tag":"Optimus供应商"},{"code":"300580","name":"贝斯特","tag":"丝杠"}],
        "your_holdings_mapped": ["伯特利(603596)"],
        "breakthrough_year": "2027-2029", "progress_pct": 35,
        "progress_desc": "特斯拉Optimus工厂自主分拣电池，国内优必选宇树智元跟进",
        "principle": "微型高功率密度伺服电机+分布式力传感器灵巧手，模仿人手指力控",
        "bottleneck": "①驱动器不够小 ②力控精度差 ③触觉传感器易坏 ④成本天价",
        "rnd_orgs": "特斯拉Optimus、优必选、宇树、智元、哈工大、浙大",
    },
    {
        "id": "robot_embodied", "area": "机器人 · 具身智能",
        "tech_name": "具身智能：物理世界模型+视频模仿学习",
        "keywords": ["具身智能","世界模型","模仿学习","Diffusion Policy","机器人自学","通用机器人"],
        "stocks": [],
        "your_holdings_mapped": ["伯特利(603596)"],
        "breakthrough_year": "2028+", "progress_pct": 20,
        "progress_desc": "Google RT-2/字节GR-2验证看视频学动作路径",
        "principle": "机器人通过视频生成学人类动作，无编程自学会换环境自适应",
        "bottleneck": "①陌生环境泛化差 ②碰撞预判不准 ③决策延迟高",
        "rnd_orgs": "DeepMind RT-2、字节/清华GR-2、斯坦福",
    },
    # ────────── 低空航天 ──────────
    {
        "id": "aviation_evtol", "area": "低空 · eVTOL",
        "tech_name": "eVTOL分布式电驱+三余度飞控",
        "keywords": ["eVTOL","垂直起降","低空经济","亿航","小鹏汇天","电动飞机","适航证","低空航线"],
        "stocks": [{"code":"688295","name":"中复神鹰","tag":"碳纤维结构件"},{"code":"600862","name":"中航高科","tag":"碳纤维复材"}],
        "your_holdings_mapped": ["中复神鹰(688295)"],
        "breakthrough_year": "商业运营2026-2028", "progress_pct": 55,
        "progress_desc": "亿航EH216-S已获TC+AC全球首家商运，小鹏汇天2026交付",
        "principle": "分布式多旋翼+三余度飞控，纯电动垂直起降无跑道",
        "bottleneck": "①电池能量密度 ②噪音抑制 ③适航安全冗余",
        "rnd_orgs": "亿航(已商运)、小鹏汇天、大疆",
    },
    {
        "id": "satellite_internet", "area": "航天 · 卫星互联网",
        "tech_name": "卫星互联网GW星座：中国版Starlink",
        "keywords": ["卫星互联网","低轨卫星","GW星座","星网","中国卫通","卫星发射"],
        "stocks": [{"code":"601698","name":"中国卫通","tag":"卫星通信"},{"code":"001270","name":"铖昌科技","tag":"相控阵芯片"},
                   {"code":"600387","name":"信科移动","tag":"卫星通信"}],
        "your_holdings_mapped": [],
        "breakthrough_year": "2026-2030", "progress_pct": 25,
        "progress_desc": "GW星座计划1.3万颗，2026-2027密集发射",
        "principle": "中国版Starlink，低轨卫星组网<1.3万颗全球宽带",
        "bottleneck": "①火箭运力不足 ②卫星批产良率 ③频轨资源争夺",
        "rnd_orgs": "中国星网(GW)、中国卫通、银河航天",
    },
]

# 快速查找
TECH_ID_MAP: Dict[str, Dict] = {t["id"]: t for t in TECH_RADAR_CONFIG}

__all__ = ["HOLDINGS", "HOLDING_CODE_MAP", "TECH_RADAR_CONFIG", "TECH_ID_MAP"]
